# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  nhonojthangfire:
    image: nhonojthangfire
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5115:5115
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
